# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
txt = "The diameter of {planet} is {diameter:.2f} kilometers."
print(txt.format(planet = "Earth",diameter = 12742))

The diameter of Earth is 12742.00 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(shape=10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
np.linspace(start=20,stop=35,num=15,dtype=np.int)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [13]:
arr = np.concatenate((a, b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [15]:
data = {'Name': ['diana', 'nick', 'krish'],
        'Age': [20, 21, 19]}
  

In [16]:
data

{'Name': ['diana', 'nick', 'krish'], 'Age': [20, 21, 19]}

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
dRan1 = pd.date_range(start ='1-1-2023', end='10-02-2023',periods = 40)
  
dRan1

DatetimeIndex([          '2023-01-01 00:00:00',
               '2023-01-08 00:36:55.384615384',
               '2023-01-15 01:13:50.769230769',
               '2023-01-22 01:50:46.153846154',
               '2023-01-29 02:27:41.538461538',
               '2023-02-05 03:04:36.923076923',
               '2023-02-12 03:41:32.307692308',
               '2023-02-19 04:18:27.692307692',
               '2023-02-26 04:55:23.076923077',
               '2023-03-05 05:32:18.461538462',
               '2023-03-12 06:09:13.846153846',
               '2023-03-19 06:46:09.230769231',
               '2023-03-26 07:23:04.615384616',
                         '2023-04-02 08:00:00',
               '2023-04-09 08:36:55.384615385',
               '2023-04-16 09:13:50.769230770',
               '2023-04-23 09:50:46.153846154',
               '2023-04-30 10:27:41.538461538',
               '2023-05-07 11:04:36.923076924',
               '2023-05-14 11:41:32.307692308',
               '2023-05-21 12:18:27.6923

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [18]:
lists =np.array([[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]])

In [19]:
df = pd.DataFrame({'Column1': lists[:, 0], 'Column2': lists[:, 1],'Column3': lists[:, 2]})

In [20]:
df

Column1 Column2 Column3
0       1     aaa      22
1       2     bbb      25
2       3     ccc      24